### ISSUE TITLE
Support hiding tabs for routes

### ISSUE THREAD

**Issue by EvanBacon** [okwasniewski/react-native-bottom-tabs#41]
In React Navigation, you can pass the following to prevent a tab from rendering in the bar:

```js
  tabBarButton: (props) => {
    return null;
  }
```

This is one of the more common properties in React Navigation's tab bar system.

**Comment by okwasniewski** [comment]
Hey, thanks for opening the issue!

I've tried to make it work, but the built-in TabView (or UITabBarController for UIKit) doesn't support this. 

Pages are tied to Tab Bar Items. What's the real-world use case for this? I think you can achieve a similar stuff using Stack Navigator if you want to have hidden routes

**Comment by okwasniewski** [comment]
Hey, @EvanBacon I was exploring how can we support this feature, due to native limitations is not so simple but I think I got a solution that also respects native behaviour. 

You can pass `hidden: true` (we can also make `tabBarButton: () => null;` work if necessary) and the tab is hidden until user navigates to it programatically, when he leaves the tab it disappears. 

Do you think this would solve your use case? 

https://github.com/user-attachments/assets/3fb6a9a2-c52c-48d9-8968-ac890761f64e
