### ISSUE TITLE
Implement `backBehavior`

### ISSUE THREAD

**Issue by okwasniewski** [okwasniewski/react-native-bottom-tabs#69]
Native Bottom Tabs are missing this prop from JS Tabs, this can be replicated almost 1:1 as it lays on the JS side: 

### `backBehavior`

This controls what happens when goBack is called in the navigator. This includes pressing the device's back button or back gesture on Android.

It supports the following values:

- `firstRoute` - return to the first screen defined in the navigator (default)
- `initialRoute` - return to initial screen passed in initialRouteName prop, if not passed, defaults to the first screen
- `order` - return to screen defined before the focused screen
- `history` - return to last visited screen in the navigator; if the same screen is visited multiple times, the older entries are dropped from the history
- `none` - do not handle back button

**Comment by shubhamguptadream11** [comment]
Let me describe 2 cases regarding navigation.

**1st Case**: Using `createNativeBottomTabNavigator`

```
const Tab = createNativeBottomTabNavigator();

function NativeBottomTabs() {
  return (
    <Tab.Navigator
      backBehavior="history"
      tabBarInactiveTintColor="#C57B57"
    >
      <Tab.Screen
        name="Article"
        component={Article}
        options={{
          tabBarBadge: "10",
          tabBarIcon: ({ focused }) =>
            focused
              ? require('../../assets/icons/person_dark.png')
              : require('../../assets/icons/article_dark.png'),
        }}
      />
      <Tab.Screen
        name="Albums"
        component={Albums}
        options={{
          tabBarIcon: () => require('../../assets/icons/grid_dark.png'),
        }}
      />
    </Tab.Navigator>
  );
}

```
In this setup:

- **Navigation Setup:** We are using `createNativeBottomTabNavigator`, which relies on useNavigationBuilder from react-navigation.
- **Back Behavior:** Here, backBehavior="history" works as expected, correctly handling all back navigation scenarios in "history" mode.
- **Back Navigation:** When navigating back from screens within this navigator using:
```
const navigation = useNavigation();
navigation.goBack();
```
navigation behaves correctly because `useNavigationBuilder` manages the navigation state and shares it with the useNavigation() hook.

**2nd Case: Using a Custom Tab Component (TabView)**

```
<TabView
  ignoresTopSafeArea={ignoresTopSafeArea}
  sidebarAdaptable
  disablePageAnimations={disablePageAnimations}
  scrollEdgeAppearance={scrollEdgeAppearance}
  navigationState={{ index, routes }}
  onIndexChange={setIndex}
  renderScene={renderScene}
  barTintColor={barTintColor}
  translucent={translucent}
  rippleColor={rippleColor}
  activeIndicatorColor={activeIndicatorColor}
/>

```
In this case:

- **Manual State Handling**: Since we are manually controlling the state with { index, routes }, TabView doesn’t have automatic back navigation handling like createNativeBottomTabNavigator.
- **Back Navigation:** When calling:
```
const navigation = useNavigation();
navigation.goBack();
```
at the screen level, goBack() doesn't work because TabView lacks an internal navigation state manager like useNavigationBuilder. The state here needs to be managed separately.

@okwasniewski  **I just want to know to more about what is the expectation here?**

**Comment by okwasniewski** [comment]
Hey @shubhamguptadream11,

It should be handled *only* in the React Navigation scenario. 

Now that I look at it it seems already handled: https://github.com/okwasniewski/react-native-bottom-tabs/blob/2ef84643d5e2ee2fb523f3434de2912804222bb9/src/react-navigation/navigators/createNativeBottomTabNavigator.tsx#L64

We are only missing documentation about this prop 🤣

**Comment by shubhamguptadream11** [comment]
Haha, exactly! 😄 I was going in circles wondering if there was anything to fix because everything seemed to be working perfectly.

Ok so, I'll go ahead and update the docs then.

**Comment by afkcodes** [comment]
how do you handle this when you are using it in a standalone mode  ? @okwasniewski
